### ISSUE TITLE
DataCleaner

### ISSUE THREAD

**Issue by djcaraballo** [DanielMulitauopele/teller#6]
Complete and test data cleaner.

**Comment by 30ozSteak** [comment]
Are we going to super worry about a data cleaner? or are we going to try graphql?

**Comment by djcaraballo** [comment]
I’m going to try and set one up for now just so we have one. If I’m not mistaken, we’re planning on adding GraphQL as a stretch, so I’d rather have it and not need it than need it and not have it. What do you think?

**Comment by 30ozSteak** [comment]
👍 ok got it, sounds good!
